package com.bestintraday;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import org.json.JSONArray;
import org.json.JSONObject;
import com.chaquo.python.Python;
import com.chaquo.python.PyObject;

public class MainActivity extends Activity {
 private static final String PREFS="best_intraday_upstox",TOKEN="upstox_token",TOTAL="total_capital",POSITION="position_capital",LIVE="live_mode";
 private static final int BG=Color.rgb(5,14,25), PANEL=Color.rgb(8,27,42), PANEL2=Color.rgb(13,38,56), TEXT=Color.rgb(241,248,250), MUTED=Color.rgb(145,166,181), CYAN=Color.rgb(0,196,255), GREEN=Color.rgb(21,226,119), RED=Color.rgb(255,72,82), LINE=Color.rgb(25,58,78), AMBER=Color.rgb(255,190,63), PURPLE=Color.rgb(126,91,255);
 private LinearLayout root,content,bottomNav; private EditText tokenInput,totalInput,positionInput; private RadioButton liveRadio,manualRadio; private String screen="dashboard"; private JSONObject snapshot=new JSONObject();
 private final ScheduledExecutorService refresh=Executors.newSingleThreadScheduledExecutor(); private final NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("en","IN"));
 private String money(double v){return money.format(v);}
 private int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);} 
 private GradientDrawable bg(int c,int s,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(s!=Color.TRANSPARENT)g.setStroke(dp(1),s);return g;}
 private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return t;}
 private TextView label(String s){TextView t=text(s.toUpperCase(Locale.US),10,MUTED,true);t.setLetterSpacing(.08f);return t;}
 private void gap(LinearLayout l,int h){TextView v=new TextView(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(h)));}
 private void gapH(LinearLayout l,int w){TextView v=new TextView(this);l.addView(v,new LinearLayout.LayoutParams(dp(w),1));}
 private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(14),dp(12),dp(14),dp(12));l.setBackground(bg(PANEL,LINE,15));return l;}
 private TextView value(String s,float size,int c){TextView t=text(s,size,c,true);t.setPadding(0,dp(4),0,0);return t;}
 private TextView button(String s,boolean primary){TextView t=text(s,12,TEXT,true);t.setGravity(Gravity.CENTER);t.setBackground(bg(primary?CYAN:PANEL2,primary?CYAN:LINE,12));t.setMinHeight(dp(46));return t;}
 private TextView pill(String s,int color){TextView t=text(s,10,color,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(5),dp(10),dp(5));t.setBackground(bg(Color.argb(55,Color.red(color),Color.green(color),Color.blue(color)),color,12));return t;}
 private void addTitle(LinearLayout l,String title,String sub){TextView h=text(title,22,TEXT,true);l.addView(h);if(sub!=null){TextView q=text(sub,11,MUTED,false);q.setPadding(0,dp(3),0,dp(10));l.addView(q);}}
 private void addMetricRow(LinearLayout l,String a,String av,String b,String bv,String c,String cv){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.addView(metric(a,av),new LinearLayout.LayoutParams(0,dp(78),1));gapH(r,7);r.addView(metric(b,bv),new LinearLayout.LayoutParams(0,dp(78),1));gapH(r,7);r.addView(metric(c,cv),new LinearLayout.LayoutParams(0,dp(78),1));l.addView(r);}
 private LinearLayout metric(String title,String val){LinearLayout c=card();c.addView(label(title));c.addView(value(val,16,TEXT));return c;}
 private LinearLayout section(String title){LinearLayout c=card();TextView h=text(title,13,CYAN,true);c.addView(h);return c;}
 private EditText field(String hint,boolean secret){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(TEXT);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);e.setBackground(bg(PANEL2,LINE,12));e.setInputType(secret?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setMinimumHeight(dp(50));return e;}
 @Override protected void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},44);buildShell();refresh.scheduleAtFixedRate(this::refreshSnapshot,1,5,TimeUnit.SECONDS);}
 private void buildShell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(14),dp(10),dp(14),dp(7));TextView menu=text("☰",25,TEXT,false);menu.setGravity(Gravity.CENTER);header.addView(menu,new LinearLayout.LayoutParams(dp(38),dp(54)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.addView(text("BEST INTRADAY",22,TEXT,true));titles.addView(text("6X LIVE TRADING",10,MUTED,true));header.addView(titles,new LinearLayout.LayoutParams(0,dp(54),1));TextView badge=pill("●  6X",GREEN);header.addView(badge,new LinearLayout.LayoutParams(dp(70),dp(34)));root.addView(header);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(4),dp(12),dp(14));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));bottomNav=new LinearLayout(this);bottomNav.setGravity(Gravity.CENTER);bottomNav.setPadding(dp(6),dp(5),dp(6),dp(6));bottomNav.setBackground(bg(PANEL,LINE,0));root.addView(bottomNav,new LinearLayout.LayoutParams(-1,dp(64)));setContentView(root);showScreen("dashboard");}
 private void nav(String id,String icon,String title){TextView t=text(icon+"\n"+title,9,id.equals(screen)?CYAN:MUTED,true);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(4),0,0);t.setOnClickListener(v->showScreen(id));bottomNav.addView(t,new LinearLayout.LayoutParams(0,dp(54),1));}
 private void rebuildNav(){bottomNav.removeAllViews();nav("dashboard","⌂","Dashboard");nav("positions","◈","Positions");nav("trades","▤","Trades");nav("watchlist","◉","Watchlist");nav("settings","⚙","Settings");}
 private void showScreen(String id){screen=id;content.removeAllViews();rebuildNav();try{if("dashboard".equals(id))dashboard();else if("positions".equals(id))positionsScreen();else if("trades".equals(id))tradesScreen();else if("watchlist".equals(id))watchlistScreen();else if("settings".equals(id))settingsScreen();else if("strategy".equals(id))strategyScreen();else if("funds".equals(id))fundsScreen();else if("activity".equals(id))activityScreen();}catch(Exception ignored){}}
 private void engineBanner(LinearLayout l){LinearLayout c=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView dot=pill(snapshot.optBoolean("running",false)?"●  LIVE":"●  OFFLINE",snapshot.optBoolean("running",false)?GREEN:RED);r.addView(dot);gapH(r,8);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.addView(text(snapshot.optBoolean("running",false)?"Engine Running":"Engine Ready",15,snapshot.optBoolean("running",false)?GREEN:TEXT,true));x.addView(text("Connected to Upstox • 6X strategy",10,MUTED,false));r.addView(x,new LinearLayout.LayoutParams(0,dp(50),1));c.addView(r);l.addView(c);}
 private void dashboard() throws Exception{addTitle(content,"Dashboard","6X momentum breakout • live terminal");engineBanner(content);gap(content,8);addMetricRow(content,"TOTAL CAPITAL",money(snapshot.optDouble("total_capital",5000000)),"DEPLOYED",money(deployedValue()),"REMAINING",money(Math.max(0,snapshot.optDouble("total_capital",5000000)-deployedValue())));gap(content,8);LinearLayout p=card();p.addView(label("TODAY'S PERFORMANCE"));double pnl=dayPnl();TextView pv=value(money(pnl),23,pnl>=0?GREEN:RED);p.addView(pv);p.addView(text("Realized P&L  •  Win rate "+winRate(),10,MUTED,false));content.addView(p);gap(content,8);LinearLayout funds=card();LinearLayout fr=new LinearLayout(this);fr.setGravity(Gravity.CENTER_VERTICAL);fr.addView(text("Upstox Funds (Live)",13,TEXT,true),new LinearLayout.LayoutParams(0,dp(34),1));fr.addView(pill("↻ Refresh",CYAN));funds.addView(fr);JSONObject f=snapshot.optJSONObject("funds");double avail=0,equity=0;if(f!=null){JSONObject a=f.optJSONObject("available_to_trade");if(a!=null)avail=a.optDouble("total",0);equity=f.optDouble("equity",0);}LinearLayout fm=new LinearLayout(this);fm.addView(fundItem("Available Cash",money(avail)),new LinearLayout.LayoutParams(0,dp(60),1));gapH(fm,8);fm.addView(fundItem("Total Equity",money(equity)),new LinearLayout.LayoutParams(0,dp(60),1));funds.addView(fm);funds.setOnClickListener(v->showScreen("funds"));content.addView(funds);gap(content,8);addMetricRow(content,"OPEN POSITIONS",String.valueOf(posCount()),"TODAY'S TRADES",String.valueOf(tradeCount()),"WIN RATE",winRate());gap(content,8);LinearLayout scan=section("LIVE MARKET SCAN");scan.addView(text("492 stocks scanned   •   "+(snapshot.optBoolean("running",false)?"Scanning…":"Engine offline"),11,TEXT,false));scan.addView(text("6X Strategy   •   EMA200 + Volume 6X + 20-bar high",10,MUTED,false));scan.setOnClickListener(v->showScreen("watchlist"));content.addView(scan);gap(content,8);LinearLayout pos=section("OPEN POSITIONS");pos.addView(text(positionSummary(),11,TEXT,false));pos.setOnClickListener(v->showScreen("positions"));content.addView(pos);gap(content,8);LinearLayout tr=section("TODAY'S TRADES");tr.addView(text(tradeSummary(),11,TEXT,false));tr.setOnClickListener(v->showScreen("trades"));content.addView(tr);gap(content,8);LinearLayout ac=section("LIVE ACTIVITY LOG");ac.addView(text(activitySummary(),11,TEXT,false));ac.setOnClickListener(v->showScreen("activity"));content.addView(ac);}
 private LinearLayout fundItem(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.addView(text(a,9,MUTED,true));c.addView(text(b,14,TEXT,true));return c;}
 private void positionsScreen() throws Exception{addTitle(content,"Open Positions",posCount()+" Positions");JSONArray ps=snapshot.optJSONArray("positions");if(ps==null||ps.length()==0){empty("No open positions","Signals are monitored in the background.");return;}for(int i=0;i<ps.length();i++){JSONObject x=ps.getJSONObject(i);double entry=x.optDouble("entry"),qty=x.optDouble("qty"),stop=x.optDouble("stop",0);LinearLayout c=card();LinearLayout h=new LinearLayout(this);h.addView(text(x.optString("symbol","UNKNOWN"),15,TEXT,true),new LinearLayout.LayoutParams(0,dp(30),1));h.addView(pill(x.optBoolean("active")?"TSL ACTIVE":"WAITING +1%",x.optBoolean("active")?GREEN:AMBER));c.addView(h);c.addView(text("NSE   •   Qty "+String.format(Locale.US,"%.0f",qty),10,MUTED,false));c.addView(text("Avg  "+money(entry)+"        TSL "+(stop>0?money(stop):"—"),12,TEXT,true));content.addView(c);gap(content,7);}TextView sq=button("SQUARE OFF ALL",false);sq.setBackground(bg(RED,RED,12));content.addView(sq);}
 private void tradesScreen() throws Exception{addTitle(content,"Today's Trades",tradeCount()+" trades");addMetricRow(content,"TOTAL TRADES",String.valueOf(tradeCount()),"PROFITABLE",String.valueOf(winCount()),"LOSS",String.valueOf(lossCount()));gap(content,8);LinearLayout p=card();p.addView(label("TOTAL P&L"));p.addView(value(money(dayPnl()),20,dayPnl()>=0?GREEN:RED));p.addView(text("Win rate  "+winRate(),11,MUTED,false));content.addView(p);gap(content,8);JSONArray tr=snapshot.optJSONArray("trades");if(tr!=null)for(int i=0;i<tr.length();i++){JSONObject x=tr.getJSONObject(i);double pl=x.optDouble("pnl");LinearLayout r=card();LinearLayout h=new LinearLayout(this);h.addView(text(x.optString("symbol"),13,TEXT,true),new LinearLayout.LayoutParams(0,dp(28),1));h.addView(text(money(pl),13,pl>=0?GREEN:RED,true));r.addView(h);r.addView(text(x.optString("time")+"   BUY "+String.format(Locale.US,"%.2f",x.optDouble("entry"))+"  →  SELL "+String.format(Locale.US,"%.2f",x.optDouble("exit")),10,MUTED,false));r.addView(text(x.optString("reason","TSL"),10,pl>=0?GREEN:RED,true));content.addView(r);gap(content,6);}}
 private void watchlistScreen() throws Exception{addTitle(content,"Live Market Scan","Scanning • 6X Strategy");addMetricRow(content,"STOCKS SCANNED","492","SIGNALS TODAY",String.valueOf(tradeCount()),"ACTIVE FILTERS","6X");gap(content,8);String[] demo={"COALINDIA","POWERGRID","NTPC","BEL","ADANIPORTS","JSWSTEEL"};for(String s:demo){LinearLayout c=card();LinearLayout h=new LinearLayout(this);h.addView(text(s,13,TEXT,true),new LinearLayout.LayoutParams(0,dp(30),1));h.addView(pill("6X  BUY",GREEN));c.addView(h);c.addView(text("Vol ≥ 6X • Breakout • Above EMA200",10,MUTED,false));content.addView(c);gap(content,6);}}
 private void strategyScreen() throws Exception{addTitle(content,"Strategy Details","Exact same logic as 6X backtest");LinearLayout c=card();c.addView(text("🎯  6X INTRADAY STRATEGY",15,CYAN,true));c.addView(text("High Momentum Breakout Strategy",10,MUTED,false));gap(c,10);c.addView(rule("1. EMA 200","Price must be above EMA 200",CYAN));c.addView(rule("2. Volume > 6X","Current volume ≥ 6X × 20-bar average",GREEN));c.addView(rule("3. 20 Bar High","Price must break previous 20-candle high",AMBER));c.addView(rule("4. Position Size",money(positionValue())+" per stock (configurable)",PURPLE));c.addView(rule("5. TSL Activation","After +1% profit",AMBER));c.addView(rule("6. Trailing Stop","1% from highest price • NO EOD exit",RED));content.addView(c);gap(content,8);LinearLayout note=card();note.addView(text("✓ Exact same logic as backtest (6X)",12,GREEN,true));note.addView(text("No EOD exit. TSL only.",11,TEXT,false));content.addView(note);}
 private TextView rule(String a,String b,int c){TextView t=text(a+"\n"+b,12,TEXT,true);t.setPadding(0,dp(8),0,dp(8));return t;}
 private void fundsScreen() throws Exception{addTitle(content,"Funds & Capital","Upstox account and strategy capital");JSONObject f=snapshot.optJSONObject("funds");double avail=0,equity=0;if(f!=null){JSONObject a=f.optJSONObject("available_to_trade");if(a!=null)avail=a.optDouble("total",0);equity=f.optDouble("equity",0);}LinearLayout c=card();c.addView(text("Upstox Account Funds",13,CYAN,true));c.addView(text("Available Cash",10,MUTED,false));c.addView(value(money(avail),18,TEXT));c.addView(text("Total Equity",10,MUTED,false));c.addView(value(money(equity),18,TEXT));content.addView(c);gap(content,8);LinearLayout s=card();s.addView(text("Strategy Capital",13,CYAN,true));s.addView(text("Total Capital    "+money(snapshot.optDouble("total_capital",5000000)),11,TEXT,false));s.addView(text("Deployed         "+money(deployedValue()),11,TEXT,false));s.addView(text("Remaining        "+money(Math.max(0,snapshot.optDouble("total_capital",5000000)-deployedValue())),11,TEXT,false));content.addView(s);gap(content,8);LinearLayout p=card();p.addView(text("Today's P&L",13,CYAN,true));p.addView(text("Realized P&L     "+money(dayPnl()),12,dayPnl()>=0?GREEN:RED,true));p.addView(text("Unrealized P&L   —",12,GREEN,true));p.addView(text("Total P&L        "+money(dayPnl()),12,dayPnl()>=0?GREEN:RED,true));content.addView(p);}
 private void activityScreen() throws Exception{addTitle(content,"Live Activity Log","Engine events • newest first");JSONArray ev=snapshot.optJSONArray("events");if(ev==null||ev.length()==0){empty("No events yet","Start the engine to see live activity.");return;}for(int i=0;i<ev.length();i++){JSONObject x=ev.getJSONObject(i);String type=x.optString("type","EVENT");int col="ERROR".equals(type)?RED:("TSL_ON".equals(type)?GREEN:CYAN);LinearLayout c=card();c.addView(text(x.optString("time")+"   "+type,10,col,true));c.addView(text(x.optString("sym","")+"  "+x.optString("text","")+(x.has("price")?"  ₹"+String.format(Locale.US,"%.2f",x.optDouble("price")):""),11,TEXT,false));content.addView(c);gap(content,5);}}
 private void settingsScreen(){addTitle(content,"Settings","Upstox + capital + execution controls");content.addView(label("UPSTOX API CONFIGURATION"));gap(content,6);tokenInput=field("Access Token",true);content.addView(tokenInput);totalInput=field("Total Capital (₹)",false);positionInput=field("Per Stock Capital (₹)",false);loadPrefs();TextView conn=text("●  "+(tokenInput.getText().length()>0?"Connected / token saved locally":"Not connected"),11,tokenInput.getText().length()>0?GREEN:AMBER,true);conn.setPadding(dp(4),dp(7),0,dp(10));content.addView(conn);TextView test=button("TEST CONNECTION",true);test.setOnClickListener(v->Toast.makeText(this,"Connection test requested",Toast.LENGTH_SHORT).show());content.addView(test);gap(content,12);content.addView(label("TRADING CONFIGURATION"));gap(content,6);content.addView(totalInput);gap(content,6);content.addView(positionInput);gap(content,12);content.addView(label("TRADING MODE"));RadioGroup g=new RadioGroup(this);manualRadio=new RadioButton(this);manualRadio.setText("Manual Mode (No real orders)");manualRadio.setTextColor(TEXT);liveRadio=new RadioButton(this);liveRadio.setText("Live Mode (Real Orders)");liveRadio.setTextColor(TEXT);boolean live=getSharedPreferences(PREFS,MODE_PRIVATE).getBoolean(LIVE,false);liveRadio.setChecked(live);manualRadio.setChecked(!live);g.addView(liveRadio);g.addView(manualRadio);content.addView(g);gap(content,12);TextView save=button("SAVE SETTINGS",true);save.setOnClickListener(v->{savePrefs();Toast.makeText(this,"Settings saved",Toast.LENGTH_SHORT).show();});content.addView(save);gap(content,10);TextView start=button("START ENGINE",true);start.setOnClickListener(v->startEngine());content.addView(start);gap(content,6);TextView stop=button("STOP ENGINE",false);stop.setOnClickListener(v->stopEngine());content.addView(stop);gap(content,12);LinearLayout lock=section("STRATEGY LOCK");lock.addView(text("ENTRY",10,CYAN,true));lock.addView(text("Close > EMA200\nVolume ≥ 6× 20-bar volume MA\nClose > previous 20-bar high",12,TEXT,false));lock.addView(text("EXIT",10,AMBER,true));lock.addView(text("+1% activation → 1% trailing stop\nNO EOD EXIT",12,TEXT,false));lock.addView(text("POSITION",10,GREEN,true));lock.addView(text("Maximum = floor(total capital / capital per stock)",12,TEXT,false));content.addView(lock);}
 private void empty(String a,String b){LinearLayout c=card();c.addView(text(a,14,TEXT,true));c.addView(text(b,10,MUTED,false));content.addView(c);}
 private void loadPrefs(){SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);if(tokenInput!=null)tokenInput.setText(p.getString(TOKEN,""));if(totalInput!=null)totalInput.setText(p.getString(TOTAL,"5000000"));if(positionInput!=null)positionInput.setText(p.getString(POSITION,"200000"));}
 private void savePrefs(){getSharedPreferences(PREFS,MODE_PRIVATE).edit().putString(TOKEN,tokenInput==null?"":tokenInput.getText().toString().trim()).putString(TOTAL,totalInput==null?"5000000":totalInput.getText().toString().trim()).putString(POSITION,positionInput==null?"200000":positionInput.getText().toString().trim()).putBoolean(LIVE,liveRadio!=null&&liveRadio.isChecked()).apply();}
 private void startEngine(){savePrefs();String token=tokenInput==null?"":tokenInput.getText().toString().trim();if(token.isEmpty()){Toast.makeText(this,"Enter Upstox access token",Toast.LENGTH_SHORT).show();return;}double total,position;try{total=Double.parseDouble(totalInput.getText().toString());position=Double.parseDouble(positionInput.getText().toString());}catch(Exception e){Toast.makeText(this,"Enter valid capital",Toast.LENGTH_SHORT).show();return;}if(total<=0||position<=0||position>total){Toast.makeText(this,"Per-stock capital must be ≤ total capital",Toast.LENGTH_SHORT).show();return;}Intent i=new Intent(this,TradingService.class);i.setAction(TradingService.ACTION_START);i.putExtra(TradingService.EXTRA_ACCESS_TOKEN,token);i.putExtra(TradingService.EXTRA_LIVE,liveRadio.isChecked());i.putExtra(TradingService.EXTRA_TOTAL,total);i.putExtra(TradingService.EXTRA_POSITION,position);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);Toast.makeText(this,(liveRadio.isChecked()?"LIVE":"MANUAL")+" engine start requested",Toast.LENGTH_SHORT).show();}
 private void stopEngine(){Intent i=new Intent(this,TradingService.class);i.setAction(TradingService.ACTION_STOP);startService(i);Toast.makeText(this,"Stop requested",Toast.LENGTH_SHORT).show();}
 private void refreshSnapshot(){try{PyObject bridge=Python.getInstance().getModule("scanner_bridge");snapshot=new JSONObject(bridge.callAttr("snapshot").toString());runOnUiThread(()->{if(!"settings".equals(screen)){try{showScreen(screen);}catch(Exception ignored){}}});}catch(Exception ignored){}}
 private double deployedValue(){double u=0;try{JSONArray ps=snapshot.optJSONArray("positions");if(ps!=null)for(int i=0;i<ps.length();i++){JSONObject x=ps.getJSONObject(i);u+=x.optDouble("entry")*x.optDouble("qty");}}catch(Exception ignored){}return u;}
 private int posCount(){JSONArray a=snapshot.optJSONArray("positions");return a==null?0:a.length();}
 private int tradeCount(){JSONArray a=snapshot.optJSONArray("trades");return a==null?0:a.length();}
 private int winCount(){int n=0;JSONArray a=snapshot.optJSONArray("trades");if(a!=null)for(int i=0;i<a.length();i++)try{if(a.getJSONObject(i).optDouble("pnl")>0)n++;}catch(Exception ignored){}return n;}
 private int lossCount(){return Math.max(0,tradeCount()-winCount());}
 private double dayPnl(){double n=0;JSONArray a=snapshot.optJSONArray("trades");if(a!=null)for(int i=0;i<a.length();i++)try{n+=a.getJSONObject(i).optDouble("pnl");}catch(Exception ignored){}return n;}
 private String winRate(){return tradeCount()==0?"—":String.format(Locale.US,"%.1f%%",100.0*winCount()/tradeCount());}
 private double positionValue(){try{return Double.parseDouble(getSharedPreferences(PREFS,MODE_PRIVATE).getString(POSITION,"200000"));}catch(Exception e){return 200000;}}
 private String positionSummary(){JSONArray a=snapshot.optJSONArray("positions");if(a==null||a.length()==0)return "No active positions";StringBuilder s=new StringBuilder();for(int i=0;i<Math.min(3,a.length());i++)try{JSONObject x=a.getJSONObject(i);s.append(x.optString("symbol")).append("   ").append(x.optBoolean("active")?"TSL Active":"Waiting +1%").append("\n");}catch(Exception ignored){}return s.toString();}
 private String tradeSummary(){JSONArray a=snapshot.optJSONArray("trades");if(a==null||a.length()==0)return "No completed trades yet";StringBuilder s=new StringBuilder();for(int i=0;i<Math.min(4,a.length());i++)try{JSONObject x=a.getJSONObject(i);double p=x.optDouble("pnl");s.append(x.optString("symbol")).append("   ").append(money(p)).append("\n");}catch(Exception ignored){}return s.toString();}
 private String activitySummary(){JSONArray a=snapshot.optJSONArray("events");if(a==null||a.length()==0)return "No events yet";StringBuilder s=new StringBuilder();for(int i=0;i<Math.min(5,a.length());i++)try{JSONObject x=a.getJSONObject(i);s.append(x.optString("time")).append("  ").append(x.optString("type")).append("  ").append(x.optString("sym")).append("\n");}catch(Exception ignored){}return s.toString();}
 @Override protected void onDestroy(){refresh.shutdownNow();super.onDestroy();}
}